### PR TITLE
Slade a/homebrew fixes

### LINKED ISSUE #17: Homebrew
Add the homebrew tab for all the information in the info tab and necessary hooks for the db. Include implementation, design, and testing.

### PR DESCRIPTION
**Pull request by SladeAnderson**
**included**
- removed commented code
- tiny fixes/updates to subrace's & race's 

**testing**
- subrace's & race's work as intened

Fixes #17

### CODE REVIEW

File: client/src/components/infoTab/Races/races.tsx [hunk 1]
```diff
@@ -58,6 +58,9 @@ const races: Component = () => {
 
   effect(()=>{
     setSearchParam({name: dndSrdRaces().length > 0 ? currentRace()?.name : "Dragonborn"})
+
+    console.log("races",dndSrdRaces());
```
Comment (ColeHend) [inline client/src/components/infoTab/Races/races.tsx:62]: could you remove this log.

**Review by ColeHend — CHANGES_REQUESTED** [review]
Almost looks good just remove that log.

**Review by ColeHend — APPROVED** [review]
